In [3]:
import random as rd
import numpy as np
import time

In [4]:
def rejection():
    c=0.14
    p=[0.11,0.14,0.09,0.08,0.12,0.1,0.09,0.07,0.11,0.09]
    while True:
        y=int(10*rd.random())+1 #Y~U[1,10], q_i=P(Y=y_j) = 1/10 = 0.1 = qmin
        u=rd.random()
        if u<(p[y-1]/c):
            return y

#Notar que en realidad c=pmax/qmin = 0.14/0.1= 0.014. Pero como dsps en
#la condicion del if lo multiplico por qy=0.1 me estaría quedando siempre 0.14



In [5]:
def transf_inv():
    u=rd.random()
    if u<0.14:
        return 2
    elif u<0.26:
        return 5
    elif u<0.37:
        return 1
    elif u<0.48:
        return 9
    elif u<0.58:
        return 6
    elif u<0.67:
        return 10
    elif u<0.76:
        return 7
    elif u<0.85:
        return 3
    elif u<0.93:
        return 4
    else:
        return 8

In [6]:
def urna():
    #Creo el arreglo
    a=[]
    p=[0.11,0.14,0.09,0.08,0.12,0.1,0.09,0.07,0.11,0.09]
    for j in range(len(p)):
        for k in range(int(p[j]*100)):
            a.append(j+1)
    u=rd.random()
    return a[int(u*100)]

In [7]:
urna()

5

In [8]:
#Simulacion que permite ver que la v.a generada es la esperada.
def simulacion_1(n):
    start_time = time.time()
    a=np.zeros(10) #Cada elemento corresponde a las ocurrencias de su posición.
    for j in range(n):
        u=rejection()
        a[u-1]+=1 
    a=a/n
    end_time = time.time()
    return (a,end_time-start_time)

In [9]:
#Simulacion que permite ver que la v.a generada es la esperada.
def simulacion_2(n):
    start_time = time.time()
    a=np.zeros(10) #Cada elemento corresponde a las ocurrencias de su posición.
    for j in range(n):
        u=transf_inv()
        a[u-1]+=1 
    a=a/n
    end_time = time.time()
    return (a,end_time-start_time)
    

In [10]:
def simulacion_3(n):
    start_time = time.time()
    a=np.zeros(10) 
    for j in range(n):
        u=urna()
        a[u-1]+=1 
    a=a/n
    end_time = time.time()
    return (a,end_time-start_time)

In [11]:
simulacion_1(10000)

(array([0.1066, 0.1397, 0.0909, 0.0779, 0.125 , 0.0989, 0.0893, 0.0701,
        0.1142, 0.0874]),
 0.012049436569213867)

In [12]:
simulacion_2(10000)

(array([0.1097, 0.1349, 0.0876, 0.0794, 0.1162, 0.1074, 0.0892, 0.0675,
        0.1147, 0.0934]),
 0.003859996795654297)

In [13]:
simulacion_3(10000)

(array([0.1113, 0.1402, 0.0884, 0.0862, 0.1189, 0.0946, 0.0849, 0.0735,
        0.1106, 0.0914]),
 0.06606221199035645)