In [1]:
import random as rd
from math import log
import time
import numpy as np
from scipy.stats import geom

In [2]:
def geom_tr_inv1(p):
    u=rd.random()
    return int(log(1-u)/log(1-p)) + 1

In [3]:
#Utilizando la forumla recursiva
def geom_tr_inv2(p):
    u=rd.random()
    F=p          #La acumulada 
    i=1
    while u>=F:
        i+=1
        p*=(1-p)**(i-1)        #p_i=
        F+=p
    return i

In [4]:
def ensayo(p):
    u=rd.random()
    if u<p:
        return True
    else:
        return False

In [5]:
def geom_ensayos(p):
    i=1
    while ensayo(p):
        i+=1
    return i

Comparemos las 2 generadores con el de scipy

In [6]:
def sim_geom_tr_inv1(p,it):
    a=np.zeros(10)
    for j in range(it):
        u=geom_tr_inv1(p)
        if u<=10:
            a[u-1]+=1
    return a/it

In [7]:
def sim_geom_tr_inv2(p,it):
    a=np.zeros(10)
    for j in range(it):
        u=geom_tr_inv2(p)
        if u<=10:
            a[u-1]+=1
    return a/it

In [8]:
def sim_geom_ensayos(p,it):
    a=np.zeros(10)
    for j in range(it):
        u=geom_ensayos(p)
        if u<=10:
            a[u-1]+=1
    return a/it

In [9]:
def sim_scipy_geom(p,it):
    a=np.zeros(10)
    for j in range(it):
        u=geom.rvs(p)
        if u<=10:
            a[u-1]+=1
    return a/it

In [16]:
sim_geom_tr_inv1(0.8,10000)

array([7.950e-01, 1.614e-01, 3.370e-02, 8.000e-03, 1.100e-03, 6.000e-04,
       2.000e-04, 0.000e+00, 0.000e+00, 0.000e+00])

In [11]:
sim_geom_tr_inv2(0.8,10000)

array([0.8033, 0.1559, 0.0408, 0.    , 0.    , 0.    , 0.    , 0.    ,
       0.    , 0.    ])

In [12]:
sim_geom_ensayos(0.8,10000)

array([0.2009, 0.1573, 0.1226, 0.0977, 0.0801, 0.07  , 0.0537, 0.0409,
       0.0325, 0.0276])

In [13]:
sim_scipy_geom(0.8,10000)

array([7.965e-01, 1.611e-01, 3.440e-02, 6.800e-03, 1.000e-03, 2.000e-04,
       0.000e+00, 0.000e+00, 0.000e+00, 0.000e+00])